"""initial

Revision ID: 70da29b4070e
Revises: 
Create Date: 2026-04-01 09:46:24.974515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70da29b4070e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('rss_feeds', sa.JSON(), nullable=False),
    sa.Column('scraper_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('scrape_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('rate_limit_rpm', sa.Integer(), nullable=False),
    sa.Column('has_paywall', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('last_scraped_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_slug'), 'sources', ['slug'], unique=True)
    op.create_table('articles',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content_snippet', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('image_url', sa.String(length=2000), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('source_category', sa.String(length=20), nullable=False),
    sa.Column('raw_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_category'), 'articles', ['category'], unique=False)
    op.create_index(op.f('ix_articles_published_at'), 'articles', ['published_at'], unique=False)
    op.create_index('ix_articles_source_published', 'articles', ['source_id', 'published_at'], unique=False)
    op.create_index(op.f('ix_articles_url_hash'), 'articles', ['url_hash'], unique=True)
    op.create_table('scrape_runs',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('articles_found', sa.Integer(), nullable=False),
    sa.Column('articles_new', sa.Integer(), nullable=False),
    sa.Column('articles_updated', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scrape_runs')
    op.drop_index(op.f('ix_articles_url_hash'), table_name='articles')
    op.drop_index('ix_articles_source_published', table_name='articles')
    op.drop_index(op.f('ix_articles_published_at'), table_name='articles')
    op.drop_index(op.f('ix_articles_category'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_sources_slug'), table_name='sources')
    op.drop_table('sources')
    # ### end Alembic commands ###
