"""increase_category_varchar_200

Revision ID: aa9b5b389317
Revises: c1d4e7f9a2b3
Create Date: 2026-04-06 23:59:37.027662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa9b5b389317'
down_revision: Union[str, None] = 'c1d4e7f9a2b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.drop_index('ix_scrape_runs_source_slug_snapshot', table_name='scrape_runs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_scrape_runs_source_slug_snapshot', 'scrape_runs', ['source_slug_snapshot'], unique=False)
    op.alter_column('articles', 'category',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
